#+TITLE: Mini Version of User Directory Application: System
#+AUTHOR: VLEAD
#+DATE: [2016-06-07 Tue]
#+SETUPFILE: ../../org-templates/level-2.org
#+TAGS: boilerplate(b)
#+EXCLUDE_TAGS: boilerplate
#+OPTIONS: ^:nil

* Introduction

A system has clear boundaries of input, output and state.
In the context of our application, the system interacts with
the external world (through command line function calls)
and also manages the entity objects in such a way that the
system invariants are maintained. 


The system holds two state variables:

 - =user_set= :: The set of users in the system
 - =session_set= :: The set of sessions in the system

The system's inputs are in terms of /operations/.  Each
operation consists of an operation name and a sequence of
arguments.  

In this implementation, an operation is identified by a
class.  The dictionary =ops_table= maps operation names to
their corresponding classes.

Each operation is divided into five checks.  A /check/ is a
predicate that either returns true or throws an exception.

The following checks are performed:

  - Arity check :: checks if the operation has the right
       number  of arguments.

  - Type check :: checks if the arguments have the correct
       type. 

  - Auth check :: checks if the session performing the
       operation is authorized to do so.

  - State check :: checks if the operation meets all the
       constraints imposed by the state of the system
       (referential integrity constraints, etc.)
 

** Structure of each operation class

The class corresponding to each operation has five fields:

  - arg_types :: a list of type predicates.  The length of
       this list is the arity of the operation.  The arity
       check is simply a comparison of the length of this
       list with the length of the list of arguments.  Each
       predicate in the =arg_types= list is applied to the
       corresponding argument to check the type of that
       argument.

  - auth_check :: a function that checks if the  =args= (which
       may include a session) together satisfy the
       authorization conditions imposed by the operation. 

  - state_check :: a function that checks =args= and checks
       if the particular state invariant holds.

  - action :: a function on args that (presumably) changes
       the state of the system and also returns an answer.
       An exception thrown by this function indicates a
       serious failure in the application (e.g., out of
       memory error). 

* The =System= class

** Constructor

   The constructor ensures that the system ensures the presence of at least one
   user with role =admin=.

#+NAME: class_system
#+begin_src python
class System ():
    admin_user = User(name=Name(name=Config.admin_name), 
                      email=Email(email=Config.admin_email), 
                      role=Role(name=Config.admin_role))
    user_set = [admin_user]
    session_set = []

#    ops_table = {'add_user' : AddUser, 
#                 'del_user' : DelUser}

    def __init__(self):
        raise Error('Can not instantiate')

    @staticmethod
    def is_session_admin(session):
        return session.get("user").get("role").get("name") == "admin"
#+end_src

*** Test Constructor
#+NAME: test_system_constructor
#+BEGIN_SRC python
class TestSystemConstructor(TestCase):
    TESTING = True

    def create_app(self):
        app = create_app(config)
        return app

    def setUp(self):
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

    def test_system_constructor(self):
        print "test_system_constructor"
        self.assertEqual(System.user_set[0].get("email").get("email"), 
                         Config.admin_email)

    def test_is_session_admin(self):
        print "test_is_session_admin"
        admin_user = User(name=Name(name=Config.admin_name), 
                      email=Email(email=Config.admin_email), 
                      role=Role(name=Config.admin_role))
        session = Session(user=admin_user)
        System.session_set.append(session)
        self.assertEqual(System.is_session_admin(session), True)

#+END_SRC


** Arity and Type check methods 

   The =do= method is the main work-horse of =Controller=.  
#+NAME: arity_type_checks
#+BEGIN_SRC python
    @staticmethod
    def arity_check(args, n):
       if  (len(args) != n) :
          raise ArityError("arity mismatch: size of args %s does not " + 
                           "match operation arity %d" % (args, n))

    @staticmethod
    def type_check(***args, **arg_types):
        for key, value in args:
            if not arg_types[key](value):
                raise TypeError("type mismatch: argument %s is not of " + 
                                "type %s" % (value, arg_types[key]))
               
#+end_src

*** Test Arity and Type Checks
#+NAME: test_arity_and_types
#+BEGIN_SRC python
class TestSystemArityAndType(TestCase):
    TESTING = True

    def create_app(self):
        app = create_app(config)
        return app

    def setUp(self):
        db.create_all()

    def tearDown(self):
        db.session.remove()
        db.drop_all()

    def test_arity(self):
        print "test_arity"
        with self.assertRaises(ArityError):
            System.arity_check([1,2], 3)

    def test_type_checks(self):
        print "test_type_checks"
        args = {"name": Name(name="Jimi Hendrix"),
                "email": Email(email="jimi@gnu.org")
                }

        arg_types = {"name": is_name,
                     "email": is_email
                     }

        with self.assertRaises(TypeError):
            System.type_check(args, arg_types)

#+END_SRC


** =do= method 
#+begin_src python
    @staticmethod   
    def do(op, **args):
        cls = System.ops_table[op]
        arg_types  = cls.arg_types
        auth_check = cls.auth_check
        state_check = cls.state_check

        try:
            System.arity_check(args.keys(), len(arg_types.keys())
            System.type_check(args, arg_types)
            auth_check(args[1])
            state_check(args)
        except (ArityError, TypeError, AuthError, StateError) as err:
            print str(err)
        else: 
            cls.action(args)

#+end_src


* =AddUser=

#+begin_src python
class AddUser():
    arg_types = [user=is_User, session=is_Session]
    auth_check = System.is_session_admin(args["session"])

    @staticmethod
    def state_check(args):
        u = args["name"]
        s = args["session"]
        if not (s in System.session_set):
            raise StateError("user not in session %s" % s.user.name)
        if (u in System.user_set):
            raise StateError("user %s already in System" % u.name)

            
    @staticmethod
    def action(**args):
        u = args["user"]
        s = args["session"]
        System.user_set.append(u)
        return u
#+end_src

** =del_user=
** =show_users=

** =get_user_by_email=
** =make_user=
** =get_email_of_user=
** =get_name_of_user=
** =get_role_of_user=
** =login=
** =del_session=
** =show_sessions=


* Infra                                                         :boilerplate:

** sources
*** Imports 
#+name: imports_for_sources
#+BEGIN_SRC python
# -*- coding: utf-8 -*-
from runtime.objects.entities import *
from runtime.config.config import Config
from runtime.exceptions.custom_exceptions import *

#+end_src


** Tests
*** Imports 
#+name: imports_for_tests
#+BEGIN_SRC python
# -*- coding: utf-8 -*-
import unittest
from flask.ext.testing import TestCase
from runtime.utils.class_persistence_template import *
from runtime.rest.app import create_app

from system import *

config = {
    'SQLALCHEMY_DATABASE_URI': ''
}

#+end_src

*** Running tests
#+NAME: run_test_cases
#+BEGIN_SRC python
if __name__ == '__main__':
    unittest.main()

#+END_SRC


* Tangling                                                      :boilerplate:

** sources
#+BEGIN_SRC python :tangle system.py :eval no :noweb yes
<<imports_for_sources>>
<<class_system>>
<<arity_type_checks>>
#+end_src


** tests
#+BEGIN_SRC python :tangle test_system.py :eval no :noweb yes
<<imports_for_tests>>
<<test_system_constructor>>
<<test_arity_and_types>>
<<run_test_cases>>
#+end_src

